# Use a Node.js base image
FROM node:20.11.1-buster

# Set the working directory
WORKDIR /app

# Copy application files
COPY . /app

# Ensure entrypoint script is executable
RUN chmod +x /app/entrypoint.dev.sh

# Install unzip utility and any dev dependencies
RUN apt-get update && apt-get install -y unzip

# Download PocketBase without extracting
ARG PB_VERSION=0.22.20
RUN mkdir -p /app/pb \
    && wget https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip -O /tmp/pb.zip

# Install dependencies for UI
WORKDIR /app/ui
RUN npm install

# Expose the PocketBase and Vite ports
EXPOSE 8090 5173

# Use the script to start the application
ENTRYPOINT ["/app/entrypoint.dev.sh"]
